// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfsNnP_tOi4-1KYwFYwEY9KehB0OwE-FQ',
    appId: '1:974795953469:web:22380c4538d1539b8fa154',
    messagingSenderId: '974795953469',
    projectId: 'autivision-c1daf',
    authDomain: 'autivision-c1daf.firebaseapp.com',
    storageBucket: 'autivision-c1daf.appspot.com',
    measurementId: 'G-0ESZ6VRD63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXlfSscQXblKlkGy--6wFHOLDRAJhMYHM',
    appId: '1:974795953469:android:57ba205b56777a9d8fa154',
    messagingSenderId: '974795953469',
    projectId: 'autivision-c1daf',
    storageBucket: 'autivision-c1daf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAJunKlfFcuyjT6ZYBKY5Au2_ZFqKSn4',
    appId: '1:974795953469:ios:59f222bbbda5a1958fa154',
    messagingSenderId: '974795953469',
    projectId: 'autivision-c1daf',
    storageBucket: 'autivision-c1daf.appspot.com',
    iosClientId: '974795953469-b2kulp5hmo25inbtl97lo7foebb12u1u.apps.googleusercontent.com',
    iosBundleId: 'com.autivision.ta.irsyan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUAJunKlfFcuyjT6ZYBKY5Au2_ZFqKSn4',
    appId: '1:974795953469:ios:e517c1e5d94703948fa154',
    messagingSenderId: '974795953469',
    projectId: 'autivision-c1daf',
    storageBucket: 'autivision-c1daf.appspot.com',
    iosClientId: '974795953469-qkk1fq972f6sr5gnpi94utsn11jjr0sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.autivisionV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfsNnP_tOi4-1KYwFYwEY9KehB0OwE-FQ',
    appId: '1:974795953469:web:290d6fa952af37208fa154',
    messagingSenderId: '974795953469',
    projectId: 'autivision-c1daf',
    authDomain: 'autivision-c1daf.firebaseapp.com',
    storageBucket: 'autivision-c1daf.appspot.com',
    measurementId: 'G-DPVZVQFF3H',
  );
}
